Repository The-Hacker-Recipes/The-Hacker-Recipes, pull requests merged in 2025-06, with the labels that each got.

#179 Add Exegol as an advertiser
  docs/.vitepress/theme/composables/sponsors.ts
  docs/.vitepress/theme/custom.css
  docs/src/public/images/sponsors/Exegol_Logo_DarkVersion_Horizontal.svg
  docs/src/public/images/sponsors/Exegol_Logo_LightVersion_Horizontal.svg
Labels: Review effort 1/5

#170 Add ldeep alternative for readgmsapassword
  docs/src/ad/movement/dacl/readgmsapassword.md
Labels: active directory, Review effort 1/5

#172 doc(targeted-kerberoasting): add an alternative method using bloodyAD…
  docs/src/ad/movement/dacl/targeted-kerberoasting.md
Labels: active directory, Review effort 1/5

#174 Update certificate-templates.md
  docs/src/ad/movement/adcs/certificate-templates.md
Labels: Review effort 1/5

#177 Added ntlmrelayx interactive use-case
  docs/src/ad/movement/ntlm/relay.md
Labels: Review effort 1/5

#180 Add 0xblank handle updated on pages
  docs/src/ad/movement/dacl/addmember.md
  docs/src/ad/movement/dacl/readgmsapassword.md
  docs/src/ad/movement/dacl/targeted-kerberoasting.md
Labels: Review effort 1/5

#178 Update certificate-templates.md
  docs/src/ad/movement/adcs/certificate-templates.md
Labels: Review effort 2/5
