Repository The-Hacker-Recipes/The-Hacker-Recipes, pull requests merged in 2025-04, with the labels that each got.

#158 Fix command
  docs/src/ad/movement/adcs/index.md
Labels: Review effort 1/5

#159 Fix minor typo
  docs/src/ad/movement/kerberos/delegations/s4u2self-abuse.md
Labels: Review effort 1/5

#150 Add WebDAV authentication from multicast poisoning
  docs/src/ad/movement/mitm-and-coerced-authentications/webclient.md
Labels: Review effort 2/5

#145 Add Kerberos relay page
  docs/.vitepress/config.mts
  docs/src/ad/movement/kerberos/index.md
  docs/src/ad/movement/kerberos/relay.md
  docs/src/ad/movement/mitm-and-coerced-authentications/dhcpv6-spoofing.md
  docs/src/ad/movement/mitm-and-coerced-authentications/index.md
  docs/src/ad/movement/mitm-and-coerced-authentications/llmnr-nbtns-mdns-spoofing.md
Labels: Review effort 3/5

#161 Update rbcd.md
  docs/src/ad/movement/kerberos/delegations/rbcd.md
Labels: Review effort 1/5

#162 Renaming relay pages title
  docs/src/ad/movement/kerberos/relay.md
  docs/src/ad/movement/ntlm/relay.md
Labels: Review effort 1/5
