Repository The-Hacker-Recipes/The-Hacker-Recipes, pull requests merged in 2025-05, with the labels that each got.

#152 Adding variables and exegol history support
  .gitignore
  docs/.vitepress/config.mts
  docs/.vitepress/plugins/thrHistory.ts
  docs/.vitepress/theme/components/ExegolHistoryImport.vue
  docs/.vitepress/theme/index.ts
  docs/src/contributing/variables.md
  docs/src/contributing/write.md
  package-lock.json
  package.json
Labels: Review effort 3/5

#167 Update vitepress-md-var to 0.2.3 and add variable reset button
  docs/src/contributing/variables.md
  package-lock.json
  package.json
Labels: Review effort 2/5

#163 Add Unix exploit/check for ESC14
  docs/src/ad/movement/adcs/certificate-templates.md
Labels: Review effort 2/5

#164 Added DSRM article to config.mts
  docs/.vitepress/config.mts
Labels: Review effort 1/5

#166 Update unrestricted-file-upload.md
  docs/src/web/inputs/unrestricted-file-upload.md
Labels: Review effort 1/5
